### ISSUE TITLE
ClientDisconnected Error

### ISSUE THREAD

**Issue by daftcucumber** [blackcandy-org/blackcandy#401]
When playing music, it **jumps back to the beginning from the middle of the song**. I suspect it might be due to either too many concurrent operations or the song stream being sent to the client too quickly causing the client to fail to respond for an extended period.

there is the error detiles:

```
I, [2024-11-28T13:34:59.234365 #17]  INFO -- : [b747617a-ee7a-40f3-9cef-fa526130fc78]   Parameters: {"song_id"=>"415"}
I, [2024-11-28T13:35:16.966568 #17]  INFO -- : Completed 500 Internal Server Error in 17732ms (ActiveRecord: 0.3ms | Allocations: 172359)
F, [2024-11-28T13:35:16.966678 #17] FATAL -- : 
IOError (closed stream):
  /usr/local/bundle/gems/actionpack-7.1.3.2/lib/action_dispatch/http/response.rb:121:in `write'
  /usr/local/bundle/gems/actionpack-7.1.3.2/lib/action_controller/metal/live.rb:181:in `write'
  /usr/local/bundle/gems/actionpack-7.1.3.2/lib/action_controller/metal/live.rb:295:in `rescue in block (2 levels) in process'
  /usr/local/bundle/gems/actionpack-7.1.3.2/lib/action_controller/metal/live.rb:292:in `block (2 levels) in process'
  /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/concurrency/share_lock.rb:162:in `sharing'
  /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/dependencies/interlock.rb:37:in `running'
  /usr/local/bundle/gems/actionpack-7.1.3.2/lib/action_controller/metal/live.rb:282:in `block in process'
  /usr/local/bundle/gems/actionpack-7.1.3.2/lib/action_controller/metal/live.rb:368:in `block in new_controller_thread'


F, [2024-11-28T13:35:16.966710 #17] FATAL -- : 
ActionController::Live::ClientDisconnected (client disconnected):
  /usr/local/bundle/gems/actionpack-7.1.3.2/lib/action_controller/metal/live.rb:190:in `write'
  /app/app/controllers/concerns/transcoded_stream_concern.rb:24:in `block (3 levels) in new'
  /app/app/models/stream.rb:34:in `block in each'
  /app/app/models/stream.rb:32:in `popen'
  /app/app/models/stream.rb:32:in `each'
  /app/app/controllers/concerns/transcoded_stream_concern.rb:23:in `block (2 levels) in new'
  /app/app/controllers/concerns/transcoded_stream_concern.rb:22:in `open'
  /app/app/controllers/concerns/transcoded_stream_concern.rb:22:in `block in new'
  /usr/local/bundle/gems/actionpack-7.1.3.2/lib/action_controller/metal/live.rb:354:in `send_stream'
  /app/app/controllers/concerns/transcoded_stream_concern.rb:21:in `new'
  /usr/local/bundle/gems/actionpack-7.1.3.2/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
  /usr/local/bundle/gems/actionpack-7.1.3.2/lib/abstract_controller/base.rb:224:in `process_action'
  /usr/local/bundle/gems/actionpack-7.1.3.2/lib/action_controller/metal/rendering.rb:165:in `process_action'
  /usr/local/bundle/gems/actionpack-7.1.3.2/lib/abstract_controller/callbacks.rb:259:in `block in process_action'
  /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:110:in `run_callbacks'
  /usr/local/bundle/gems/actionpack-7.1.3.2/lib/abstract_controller/callbacks.rb:258:in `process_action'
  /usr/local/bundle/gems/actionpack-7.1.3.2/lib/action_controller/metal/rescue.rb:25:in `process_action'
  /usr/local/bundle/gems/actionpack-7.1.3.2/lib/action_controller/metal/instrumentation.rb:74:in `block in process_action'
  /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/notifications.rb:206:in `block in instrument'
  /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
  /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/notifications.rb:206:in `instrument'
  /usr/local/bundle/gems/actionpack-7.1.3.2/lib/action_controller/metal/instrumentation.rb:73:in `process_action'
  /usr/local/bundle/gems/actionpack-7.1.3.2/lib/action_controller/metal/params_wrapper.rb:261:in `process_action'
  /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/railties/controller_runtime.rb:32:in `process_action'
  /usr/local/bundle/gems/actionpack-7.1.3.2/lib/abstract_controller/base.rb:160:in `process'
  /usr/local/bundle/gems/actionview-7.1.3.2/lib/action_view/rendering.rb:40:in `process'
  /usr/local/bundle/gems/actionpack-7.1.3.2/lib/action_controller/metal/live.rb:291:in `block (2 levels) in process'
  /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/concurrency/share_lock.rb:162:in `sharing'
  /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/dependencies/interlock.rb:37:in `running'
  /usr/local/bundle/gems/actionpack-7.1.3.2/lib/action_controller/metal/live.rb:282:in `block in process'
  /usr/local/bundle/gems/actionpack-7.1.3.2/lib/action_controller/metal/live.rb:368:in `block in new_controller_thread'
```

**Comment by daftcucumber** [comment]
The phenomenon **improved** after reducing the bitrate.

use admin account log in and change settings let the Transcode Bitrate down to the lowest gear , the frequency of the problem occurring has decreased.
